autocommit on Sat Dec 27 14:26:39 +07 2025

diff --git a/build b/build
--- a/build
+++ b/build
@@ -11,9 +11,9 @@ main() {
 update_chart_version() {
   local version=$1
   if [[ -f charts/wordpress/Chart.yaml ]]; then
-    sed -i.bak "s/^version: .*/version: ${version}/" charts/Chart.yaml
+    sed -i.bak "s/^version: .*/version: ${version}/" charts/wordpress/Chart.yaml
   else
-    echo "Error: chart/Chart.yaml not found!" >&2
+    echo "Error: chart/wordpress/Chart.yaml not found!" >&2
     exit 1
   fi
 }
